kind: Deployment
apiVersion: apps/v1

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ruthran1803/quiz-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: quiz-secrets
              key: MONGO_URI
        
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT

        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: quiz-secrets
              key: GEMINI_API_KEY

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: quiz-secrets
              key: JWT_SECRET

        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "500m"
            
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10        