apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
      - name: quiz-backend
        image: ruthran1803/quiz-backend:v2
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://ruthran_quiz:ruthran_1803@ac-z2ftgo6-shard-00-00.klktq46.mongodb.net:27017,ac-z2ftgo6-shard-00-01.klktq46.mongodb.net:27017,ac-z2ftgo6-shard-00-02.klktq46.mongodb.net:27017/quizapp?ssl=true&replicaSet=atlas-1379il-shard-0&authSource=admin&retryWrites=true&w=majority"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-service
spec:
  selector:
    app: quiz-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: ruthran1803/quiz-frontend:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend-service
spec:
  selector:
    app: quiz-frontend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer
