apiVersion: v1
kind: Secret
metadata:
  name: quiz-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://ruthran_quiz:ruthran_1803@ac-z2ftgo6-shard-00-00.klktq46.mongodb.net:27017,ac-z2ftgo6-shard-00-01.klktq46.mongodb.net:27017,ac-z2ftgo6-shard-00-02.klktq46.mongodb.net:27017/quizapp?ssl=true&replicaSet=atlas-1379il-shard-0&authSource=admin&retryWrites=true&w=majority"
  GEMINI_API_KEY: "AIzaSyC7mbIU8pSWyQH2RLvgT7I4sXKPkDnv7QQ"
  JWT_SECRET: "quiz-app-super-secret-jwt-key-2024"
